# Generated by Django 4.0.3 on 2022-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
