# Generated by Django 4.0.3 on 2022-03-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='event',
            new_name='event_pk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
